Add enable Pulp 2 and Pulpcore parameters
theforeman/puppet-foreman_proxy_content pull request #299
Opened 2020-11-23 14:31 UTC by ehelms

@ekohl I wanted to see if this what you were thinking before I went further.

2020-11-23 16:00 UTC, ekohl commented
This is indeed what I was thinking about

2020-11-23 18:04 UTC, ehelms commented on manifests/init.pp
> +  Boolean $enable_pulp2_mirror = false,
For me, that more about nomenclature. We want to stick with `pulpcore` based parameters going forward so having a `pulp` parameter that is for Pulp 2 and 3 makes it an oddball. I'd rather just have both and drop the Pulp 2 one when the time is right (which is rather close).

2020-11-24 10:55 UTC, ekohl commented on manifests/init.pp
> +  Boolean $enable_pulp2_mirror = false,
Thoughts about `$content_is_mirror`?

2020-11-24 20:52 UTC, ehelms commented on manifests/init.pp
> +  Boolean $enable_pulp2_mirror = false,
If it was internal, sure. But for a user, there is good parity in `enable_pulpcore` `enable_pulpcore_mirror`. I think there is an argument to be made for, if puppet-foreman_proxy_content is enabled, you get Pulpcore automatically as its implied. Which means we could reduce this to just the parameter `content_mirror` or `enable_content_mirror` ? But, given we already expose everything as `pulpcore` (https://github.com/theforeman/puppet-foreman_proxy_content/pull/299/files#diff-c6c3a824d185ff01e063011517a1b13a604dc3d7b63d1c67a30451c10df02bcbR100-R125) I am inclined to just stay with that nomenclature.

2020-11-24 23:53 UTC, ekohl requested changes
Some implementation details inline, but overall I think this looks like it's heading in the right direction.

2020-11-24 23:53 UTC, ekohl commented on manifests/init.pp
> +# $enable_pulpcore_mirror::             Whether this pulpcore deployment acts as a mirror.
Is it pulpcore or Pulpcore? Probably good to be consistent in that.

2020-11-24 23:53 UTC, ekohl commented on manifests/init.pp
> +  $enable_pulp2_rpm = $enable_yum and ($enable_pulp2 and !$proxy_pulp_yum_to_pulpcore)
Nit: the braces are redundant now
```suggestion
  $enable_pulp2_rpm = $enable_yum and $enable_pulp2 and !$proxy_pulp_yum_to_pulpcore
```

2020-11-24 23:53 UTC, ekohl commented on manifests/init.pp
> +    pulpnode_enabled => $enable_pulp2_mirror,
This logic is incorrect. In Pulp 2 there was one plugin for pulp and one for pulpnode. Enabling both at the same time is illogical and probably confuses Katello.
```suggestion
    enabled          => $enable_pulp2 and !$enable_pulp2_mirror,
    pulpnode_enabled => $enable_pulp2 and $enable_pulp2_mirror,
```

2020-11-24 23:53 UTC, ekohl commented on manifests/init.pp
> +      unless $enable_pulp2_mirror {
Can you use `unless` if there is also an `else`? Maybe it was Ruby where that's not possible.

2020-11-24 23:53 UTC, ekohl commented on spec/classes/foreman_proxy_content_spec.rb
> +      context 'without parameters' do
Technically not really correct anymore since you do set `params` by default.

2020-11-24 23:53 UTC, ekohl commented on spec/classes/foreman_proxy_content_spec.rb
> +            enable_pulp2_mirror: true
Mind sorting these?

2020-11-24 23:53 UTC, ekohl commented on manifests/init.pp
>    # TODO: doesn't allow deploying a Pulp non-mirror without Foreman
I'm still thinking how we can achieve this but it's probably easier once we get rid of Pulp 2.

2020-11-30 13:31 UTC, ehelms commented
The more I think about this the more I am seeing these additional parameters as temporary and not needed. If we look at the current nightly situation for Katello we have the following:

 * Server: Should be Pulp 3 for content, Pulp 2 existing only to support katello-agent
 * Proxy: Pulp 3 only, with dispatch router present for katello-agent

We should be able to assume that if you are enabling `foreman_proxy_content` you are getting Pulp 3. The only option is whether or not this is a mirror installation. 

For Qpid, I think we could consider defaulting it to off on server and proxy and having users enable it going forward if they want that functionality. Especially as we consider the move is to drop Pulp 2 and have Katello own communication over the Qpid-katello-agent protocol.

2020-12-04 16:55 UTC, ekohl commented
Long term I think there are 3 deployment methods. In all of them, there should be Pulp 3.

1. Primary
.1. Deployed as part of the Foreman vhost
.2. Deployed standalone
2. Mirror
.1. Deployed standalone

Then there is the question of additional services. I think this is a summary of the status.

1.1. Pulp 2 can exist if desired for katello-agent. If so, should have qpid
1.2. Can't be properly supported until we drop Pulp 2 and Qpid?
2.1. Qpid dispatch router can be present if desired for katello-agent

Consider a scenario where server is EL7 but Smart Proxy is EL8. Let's say katello-agent is desired so the server has qpid. How does Katello know that qdrouterd is running on a Smart Proxy and can reach clients?

2021-01-12 20:25 UTC, closed without merging