Add pulpcore_django_secret_key parameter
theforeman/puppet-foreman_proxy_content pull request #331
Opened 2021-02-26 08:22 UTC by laugmanuel

Currently, the pulpcore parameter `django_secret_key` is generated/cached using `extlib` inside `puppet-pulpcore`. As the parameter is not exposed here, this breaks when using multiple puppetservers.

With this PR a user can explicitly specify that parameter. If the parameter is not set, it will still use the implementation of `puppet-pulpcore` (to not break existing installs).

2021-02-26 12:54 UTC, ekohl requested changes
Could you also add a parameter description for this?

2021-02-26 12:54 UTC, ekohl commented on manifests/init.pp
> +  Optional[String] $pulpcore_django_secret_key = $foreman_proxy_content::params::pulpcore_django_secret_key,
We've started to move static parameters to `init.pp` where possible
```suggestion
  Optional[String] $pulpcore_django_secret_key = undef,
```

2021-02-26 12:59 UTC, laugmanuel commented
> Could you also add a parameter description for this?

Seems like I always forget the same thing 🤦🏻 I've added a description for the parameter.

2021-03-23 10:52 UTC, ekohl reviewed
Overall :+1:

2021-03-23 10:52 UTC, ekohl commented on manifests/init.pp
> +  Optional[String] $pulpcore_django_secret_key = undef,
It is recommended to use at least 50 characters. Should we enforce that?
```suggestion
  Optional[String[50]] $pulpcore_django_secret_key = undef,
```

2021-03-23 16:32 UTC, ekohl approved these changes

2021-03-23 16:32 UTC, merged