Fixes #32910: Support enabling content caching for Pulp
theforeman/puppet-foreman_proxy_content pull request #372
Opened 2021-07-07 00:23 UTC by ehelms

Requires https://github.com/theforeman/puppet-pulpcore/pull/204

2021-07-07 16:28 UTC, ehelms commented
I figured exposing these was the cleanest way rather than relying on users configuring hiera.

2021-07-08 13:04 UTC, ekohl requested changes
Could you raise the minimum version in metadata.json?

2021-07-08 13:12 UTC, ehelms commented
Updated

2021-07-08 14:06 UTC, ekohl approved these changes

2021-07-08 14:21 UTC, merged