Fixes #37325 - make postgres the container gateway default DB
theforeman/puppet-foreman_proxy_content pull request #479
Opened 2024-04-05 15:31 UTC by ianballou

Draft PR to instantiate the postgres database for the container gateway. The main PR is here: https://github.com/theforeman/puppet-foreman_proxy/pull/835

I'm not totally sure if foreman_proxy_content is the proper spot to create the DB, but it seemed better than doing it in foreman_proxy and adding a postgres library requirement there.

I'm looking for general feedback on what things I might be missing between the two PRs since I don't work on Puppet modules often.

2024-04-05 15:45 UTC, ekohl requested changes
As mentioned in https://github.com/theforeman/puppet-foreman_proxy/pull/835#pullrequestreview-1983574442, I'd prefer to manage the DB there.

I do wonder about external DB support. AFAIK we don't currently support that on content proxies, but if we would then we'd need to account for it.

2024-04-05 15:45 UTC, ekohl commented on manifests/init.pp
> +    include postgresql::server::contrib
Do you need extensions from contrib?

2024-04-05 15:45 UTC, ekohl commented on manifests/init.pp
> +    include postgresql::client
Normally `client` is not needed.

2024-04-09 20:24 UTC, ianballou commented
Closing to put this work in foreman_proxy. (https://github.com/theforeman/puppet-foreman_proxy/pull/835)

2024-04-09 20:24 UTC, closed without merging