Default 8443 reverse proxy to off
theforeman/puppet-foreman_proxy_content pull request #487
Opened 2024-07-30 16:46 UTC by ehelms

2024-07-30 17:01 UTC, ekohl requested changes
I'd like to have a Redmine issue for this because I think it'll also deserve a release note. This is a backwards incompatible change now. It will also mean we disable port 8443 on existing installations. Is there an accompanying foreman-installer change to maintain it on existing installations?

2024-07-30 19:00 UTC, ehelms commented
> I'd like to have a Redmine issue for this because I think it'll also deserve a release note. This is a backwards incompatible change now. It will also mean we disable port 8443 on existing installations. Is there an accompanying foreman-installer change to maintain it on existing installations?

This feels borderline backwards incompatible? This can still be turned on, so it is backwards compatible when the option is provided.

The idea is to disable this for everyone, including upgrades. Users who need this should take a direct action to re-enable it so that they understand the choice that they are making. The only things that should be affected by this are:

 * clients that have existed for 3+ years and have not updated the katello-ca-consumer RPM
 * users using the 8443 endpoint for API access (which we are wanting to close off)

2024-07-30 19:46 UTC, ekohl commented
> This feels borderline backwards incompatible? This can still be turned on, so it is backwards compatible when the option is provided.

I meant backwards incompatible from a Puppet module point of view.

> The idea is to disable this for everyone, including upgrades. Users who need this should take a direct action to re-enable it so that they understand the choice that they are making. The only things that should be affected by this are:

Sounds fair to me. Still, an upgrade warning is IMHO a good thing for this. Better warned too often than too little.

2024-07-30 21:00 UTC, ehelms commented
> > This feels borderline backwards incompatible? This can still be turned on, so it is backwards compatible when the option is provided.
> 
> I meant backwards incompatible from a Puppet module point of view.

We could set `reverse_proxy` to `true` here to avoid this and only set it to `false` in the installer. If that's useful?


> Sounds fair to me. Still, an upgrade warning is IMHO a good thing for this. Better warned too often than too little.

What sort of upgrade warning do you envision?

2024-08-02 12:46 UTC, ekohl approved these changes
> We could set `reverse_proxy` to `true` here to avoid this and only set it to `false` in the installer. If that's useful?

The parameter already exists, so on existing installations it will be stored in the answers file already. That won't be helpful.

> What sort of upgrade warning do you envision?

Something in https://github.com/theforeman/foreman-documentation/blob/master/guides/doc-Release_Notes/topics/katello.adoc#upgrade-warnings that tells users that if they upgrade, the reverse proxy on port 8443 will be turned off. Ideally with a link to some procedure to upgrade clients and/or instructions on how to turn it back on.

2024-08-02 13:11 UTC, ehelms commented
> Something in https://github.com/theforeman/foreman-documentation/blob/master/guides/doc-Release_Notes/topics/katello.adoc#upgrade-warnings that tells users that if they upgrade, the reverse proxy on port 8443 will be turned off. Ideally with a link to some procedure to upgrade clients and/or instructions on how to turn it back on.

Got a draft up for it -- https://github.com/theforeman/foreman-documentation/pull/3180

2024-08-02 13:11 UTC, merged

2024-09-24 16:22 UTC, nixfu commented
BTW, I am not sure this is accurate.   The 443 does not reverse proxy things like the foreman API.   We use the reverse proxy on 8443 today to do foreman api calls, for things like clients checking if they are in the foreman inventory, and inserting themselves if they are not etc..

2024-09-24 16:31 UTC, evgeni commented
Correct, that's intentional